CREATE TABLE [dbo].[NominasDet]
(
	[id_det] INT NOT NULL PRIMARY KEY IDENTITY, 
	[id_cab] INT NULL,
    [id_empleado] INT NULL, 
    [valorD] NUMERIC(18, 2) NULL, 
	[valorH] NUMERIC(18, 2) NULL, 
    [lunD] FLOAT NULL, 
    [lunH] FLOAT NULL, 
	[marD] FLOAT NULL, 
    [marH] FLOAT NULL, 
	[mieD] FLOAT NULL, 
    [mieH] FLOAT NULL, 
	[jueD] FLOAT NULL, 
    [jueH] FLOAT NULL, 
	[vieD] FLOAT NULL, 
    [vieH] FLOAT NULL, 
	[sabD] FLOAT NULL, 
    [sabH] FLOAT NULL, 
	[domD] FLOAT NULL, 
    [domH] FLOAT NULL, 
    CONSTRAINT [FK_NominasDet_Trabajadores] FOREIGN KEY ([id_empleado]) REFERENCES [Trabajadores]([Id]),
)
