//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManzantinesApp.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asientos
    {
        public int Id { get; set; }
        public Nullable<int> id_proveedor { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public Nullable<System.DateTime> FechaFactura { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public string FormaPago { get; set; }
        public Nullable<bool> Pagado { get; set; }
    
        public virtual Empresas Empresas { get; set; }
        public virtual Proveedores Proveedores { get; set; }
    }
}
