//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManzantinesApp.DBContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MazantinesEntities : DbContext
    {
        public MazantinesEntities()
            : base("name=MazantinesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Empleos> Empleos { get; set; }
        public virtual DbSet<EmpleosPagos> EmpleosPagos { get; set; }
        public virtual DbSet<NominasCab> NominasCab { get; set; }
        public virtual DbSet<Trabajadores> Trabajadores { get; set; }
        public virtual DbSet<Trabajadores_Empleos> Trabajadores_Empleos { get; set; }
        public virtual DbSet<NominasDet> NominasDet { get; set; }
        public virtual DbSet<vv_nominas> vv_nominas { get; set; }
    }
}
