//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManzantinesApp.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Frutas_variedades
    {
        public int Id { get; set; }
        public Nullable<int> id_fruta { get; set; }
        public string Variedad { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        public virtual Frutas Frutas { get; set; }
    }
}
