//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManzantinesApp.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liquidaciones
    {
        public int Id { get; set; }
        public string Concepto { get; set; }
        public Nullable<int> Categoria { get; set; }
        public Nullable<decimal> Totales { get; set; }
        public Nullable<bool> Pagado { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
