//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManzantinesApp.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class NominasCab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NominasCab()
        {
            this.NominasDet = new HashSet<NominasDet>();
        }
    
        public int id_cab { get; set; }
        public Nullable<decimal> anio { get; set; }
        public Nullable<decimal> semana { get; set; }
        public Nullable<int> id_encargado { get; set; }
        public string status { get; set; }
    
        public virtual Encargados Encargados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NominasDet> NominasDet { get; set; }
    }
}
