//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManzantinesApp.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class NominasCab
    {
        public int id_cab { get; set; }
        public Nullable<decimal> anio { get; set; }
        public Nullable<decimal> semana { get; set; }
        public Nullable<int> id_encargado { get; set; }
        public string status { get; set; }
    }
}
