//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManzantinesApp.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class vv_CasasCountEmpleados
    {
        public int Id { get; set; }
        public int NroCasa { get; set; }
        public string Finca { get; set; }
        public Nullable<int> CantEmpleados { get; set; }
    }
}
