//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManzantinesApp.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class vv_empleados
    {
        public int Id { get; set; }
        public string Nro_Empleado { get; set; }
        public string Caja { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string FullName { get; set; }
        public string Encargado { get; set; }
        public string Telefono { get; set; }
        public string NroCasa { get; set; }
        public string Empresa { get; set; }
        public string Empleos { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
