//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManzantinesApp.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class vv_nominas
    {
        public Nullable<decimal> anio { get; set; }
        public Nullable<decimal> semana { get; set; }
        public Nullable<int> id_encargado { get; set; }
        public string status { get; set; }
        public int id_det { get; set; }
        public Nullable<int> id_cab { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public Nullable<decimal> baseEmpleo { get; set; }
        public Nullable<decimal> lunD { get; set; }
        public Nullable<decimal> lunH { get; set; }
        public Nullable<decimal> marD { get; set; }
        public Nullable<decimal> marH { get; set; }
        public Nullable<decimal> mieD { get; set; }
        public Nullable<decimal> mieH { get; set; }
        public Nullable<decimal> jueD { get; set; }
        public Nullable<decimal> jueH { get; set; }
        public Nullable<decimal> vieD { get; set; }
        public Nullable<decimal> vieH { get; set; }
        public Nullable<decimal> sabD { get; set; }
        public Nullable<decimal> sabH { get; set; }
        public Nullable<decimal> domD { get; set; }
        public Nullable<decimal> domH { get; set; }
    }
}
