//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManzantinesApp.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class vv_NominasEmpleadosMes
    {
        public int id_det { get; set; }
        public Nullable<decimal> Anio { get; set; }
        public Nullable<decimal> Semana { get; set; }
        public Nullable<int> id_encargado { get; set; }
        public string Nro_Empleado { get; set; }
        public string Caja { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public Nullable<System.DateTime> semanaIni { get; set; }
        public Nullable<System.DateTime> semanaFin { get; set; }
        public Nullable<int> mesIni { get; set; }
        public Nullable<double> totalD { get; set; }
        public Nullable<double> totalH { get; set; }
        public Nullable<double> valorD { get; set; }
        public Nullable<double> valorH { get; set; }
        public string Encargado { get; set; }
        public Nullable<double> TotalPago { get; set; }
    }
}
